tic
disp('0/10')
out = sim('L1_4R_B_C');

caract_4R_B_C = [out.logsout.get('U').Values.Data(end)...
    out.logsout.get('I').Values.Data(end)...
    out.logsout.get('P').Values.Data(end)...
    out.logsout.get('Q').Values.Data(end)...
    out.logsout.get('S').Values.Data(end)...
    out.logsout.get('Wh').Values.Data(end)...
    out.logsout.get('VARh').Values.Data(end)...
    out.logsout.get('VAh').Values.Data(end)...
    out.logsout.get('phi').Values.Data(end)];

disp('1/10')
%%
out2 = sim("L1_2R.slx");

caract_2R = [out2.logsout.get('U').Values.Data(end)...
    out2.logsout.get('I').Values.Data(end)...
    out2.logsout.get('P').Values.Data(end)...
    out2.logsout.get('Q').Values.Data(end)...
    out2.logsout.get('S').Values.Data(end)...
    out2.logsout.get('Wh').Values.Data(end)...
    out2.logsout.get('VARh').Values.Data(end)...
    out2.logsout.get('VAh').Values.Data(end)...
    out2.logsout.get('phi').Values.Data(end)];
disp('2/10')
%%
out3 = sim("L1_2R_B.slx");

caract_2R_B = [out3.logsout.get('U').Values.Data(end)...
    out3.logsout.get('I').Values.Data(end)...
    out3.logsout.get('P').Values.Data(end)...
    out3.logsout.get('Q').Values.Data(end)...
    out3.logsout.get('S').Values.Data(end)...
    out3.logsout.get('Wh').Values.Data(end)...
    out3.logsout.get('VARh').Values.Data(end)...
    out3.logsout.get('VAh').Values.Data(end)...
    out3.logsout.get('phi').Values.Data(end)];


disp('3/10')
%%

out4 = sim('L1_2R_C.slx');

caract_2R_C = [out4.logsout.get('U').Values.Data(end)...
    out4.logsout.get('I').Values.Data(end)...
    out4.logsout.get('P').Values.Data(end)...
    out4.logsout.get('Q').Values.Data(end)...
    out4.logsout.get('S').Values.Data(end)...
    out4.logsout.get('Wh').Values.Data(end)...
    out4.logsout.get('VARh').Values.Data(end)...
    out4.logsout.get('VAh').Values.Data(end)...
    out4.logsout.get('phi').Values.Data(end)];
disp('4/10')
%%

out5 = sim('L1_2R_B_C');

caract_2R_B_C = [out5.logsout.get('U').Values.Data(end)...
    out5.logsout.get('I').Values.Data(end)...
    out5.logsout.get('P').Values.Data(end)...
    out5.logsout.get('Q').Values.Data(end)...
    out5.logsout.get('S').Values.Data(end)...
    out5.logsout.get('Wh').Values.Data(end)...
    out5.logsout.get('VARh').Values.Data(end)...
    out5.logsout.get('VAh').Values.Data(end)...
    out5.logsout.get('phi').Values.Data(end)];
disp('5/10')
%%

out6 = sim('L1_4R');

caract_4R = [out6.logsout.get('U').Values.Data(end)...
    out6.logsout.get('I').Values.Data(end)...
    out6.logsout.get('P').Values.Data(end)...
    out6.logsout.get('Q').Values.Data(end)...
    out6.logsout.get('S').Values.Data(end)...
    out6.logsout.get('Wh').Values.Data(end)...
    out6.logsout.get('VARh').Values.Data(end)...
    out6.logsout.get('VAh').Values.Data(end)...
    out6.logsout.get('phi').Values.Data(end)];

disp('6/10')
%%


out7 = sim('L1_4R_B');

caract_4R_B = [out7.logsout.get('U').Values.Data(end)...
    out7.logsout.get('I').Values.Data(end)...
    out7.logsout.get('P').Values.Data(end)...
    out7.logsout.get('Q').Values.Data(end)...
    out7.logsout.get('S').Values.Data(end)...
    out7.logsout.get('Wh').Values.Data(end)...
    out7.logsout.get('VARh').Values.Data(end)...
    out7.logsout.get('VAh').Values.Data(end)...
    out7.logsout.get('phi').Values.Data(end)];
disp('7/10')
%%

out8 = sim('L1_4R_C');

caract_4R_C = [out8.logsout.get('U').Values.Data(end)...
    out8.logsout.get('I').Values.Data(end)...
    out8.logsout.get('P').Values.Data(end)...
    out8.logsout.get('Q').Values.Data(end)...
    out8.logsout.get('S').Values.Data(end)...
    out8.logsout.get('Wh').Values.Data(end)...
    out8.logsout.get('VARh').Values.Data(end)...
    out8.logsout.get('VAh').Values.Data(end)...
    out8.logsout.get('phi').Values.Data(end)];
disp('8/10')
%%

out9 = sim('L1_B');

caract_B = [out9.logsout.get('U').Values.Data(end)...
    out9.logsout.get('I').Values.Data(end)...
    out9.logsout.get('P').Values.Data(end)...
    out9.logsout.get('Q').Values.Data(end)...
    out9.logsout.get('S').Values.Data(end)...
    out9.logsout.get('Wh').Values.Data(end)...
    out9.logsout.get('VARh').Values.Data(end)...
    out9.logsout.get('VAh').Values.Data(end)...
    out9.logsout.get('phi').Values.Data(end)];
disp('9/10')
%%

out10 = sim('L1_C');

caract_C = [out10.logsout.get('U').Values.Data(end)...
    out10.logsout.get('I').Values.Data(end)...
    out10.logsout.get('P').Values.Data(end)...
    out10.logsout.get('Q').Values.Data(end)...
    out10.logsout.get('S').Values.Data(end)...
    out10.logsout.get('Wh').Values.Data(end)...
    out10.logsout.get('VARh').Values.Data(end)...
    out10.logsout.get('VAh').Values.Data(end)...
    out10.logsout.get('phi').Values.Data(end)];

disp('10/10')
%% TABEL DATE EXPERIMENTALE

date_matrice = [caract_2R; 
                caract_2R_B; 
                caract_2R_C; 
                caract_2R_B_C; ...
                caract_4R; 
                caract_4R_B; 
                caract_4R_C; 
                caract_4R_B_C; ...
                caract_B; 
                caract_C];

%% TABEL DATE EXPERIMENTALE
% Antet
nume_coloane = {'U_V', 'I_A', 'P_W', 'Q_VAR', 'S_VA', 'Wh_Wh', 'VARh_VARh', 'VAh_VAh', 'phi_grd'};

% Numele experimentelor
nume_linii = {'caract_2R', 'caract_2R_B', 'caract_2R_C', 'caract_2R_B_C', ...
              'caract_4R', 'caract_4R_B', 'caract_4R_C', 'caract_4R_B_C', ...
              'caract_B', 'caract_C'};

% Tabel
T_e = array2table(date_matrice, ...
    'VariableNames', nume_coloane, ...
    'RowNames', nume_linii);

Sc = T_e{:,1}.*T_e{:,2};
cos_phi = T_e{:,3}./T_e{:,5};
We = T_e{:,3}/60;
eps_Wh = (T_e{:,6} - We) ./ We * 100;
eps_Wh(abs(We) < 1e-3) = 0;
eps_S = (T_e{:,5}-Sc(:))./Sc(:)*100;
Z = abs(T_e{:,1}./T_e{:,2});
R = abs(T_e{:,3}./(T_e{:,2}.^2));
X = abs(T_e{:,4}./(T_e{:,2}.^2));
L = X/(100*pi);
C = 1./(100*pi*X);
% for i = 1:length(C)
%     if C(i)>10
%         C(i) = 1/100/pi/0.5*(1/i^2); % pentru caz rezistiv
%     end
% end

nume_coloane2 = {'Sc [VA]', 'cos \phi', 'W_e [Wh]', '\varepsilon(Wh)', '\varepsilon(S)', 'Z [ohm]', 'R [ohm]', 'L [H]', 'C [F]'};

date_matrice2 = [Sc, ...
    cos_phi,...
    We,...
    eps_Wh, ...
    eps_S,...
    Z,...
    R, ...
    L, ...
    C, ...
    ];


T_c = array2table(date_matrice2, ...
    'VariableNames', nume_coloane2, ...
    'RowNames', nume_linii);

I_complex = T_e{:,2}.*(cosd(T_e{:,9})+1i*sind(T_e{:,9}));
% phasors([50*I_complex(1) T_e{1,1}])
% phasors([50*I_complex(2) T_e{2,1}])
% phasors([50*I_complex(3) T_e{3,1}])
% phasors([50*I_complex(4) T_e{4,1}])
% phasors([50*I_complex(5) T_e{5,1}])
% phasors([50*I_complex(6) T_e{6,1}])
% phasors([50*I_complex(7) T_e{7,1}])
% phasors([50*I_complex(8) T_e{8,1}])
% phasors([50*I_complex(9) T_e{9,1}])
% phasors([50*I_complex(10) T_e{10,1}])


% Afisare diagrame in figura principala
figure('Name', 'Diagrame Fazoriale - Toate Experimentele', 'NumberTitle', 'off');
for i = 1:10
    subplot(2, 5, i); 
    cla reset;
    h = phasors([50 * I_complex(i), T_e{i, 1}]);
    if i == 1
        legend(h, {'Curent I (\times50)', 'Tensiune U [V]'}, 'Location', 'northwest');
    end
    
    if isprop(T_e, 'Properties') && ~isempty(T_e.Properties.RowNames)
        title(strrep(T_e.Properties.RowNames{i}, '_', '\_'), 'FontSize', 8);
    else
        title(['Exp ', num2str(i)], 'FontSize', 8);
    end
end

% Export tabele Excel
nume_fisier_excel = 'Rezultate_Analiza_Simulink.xlsx';
writetable(T_e, nume_fisier_excel, 'Sheet', 'Date_Experimentale', 'WriteRowNames', true);
writetable(T_c, nume_fisier_excel, 'Sheet', 'Date_Calculate', 'WriteRowNames', true);
disp(['Tabele exportate in: ', nume_fisier_excel]);

% Export diagrame individuale in folder
folder_imagini = 'Diagrame_Fazoriales';
if ~exist(folder_imagini, 'dir')
    mkdir(folder_imagini);
end

for i = 1:height(T_e)
    fig_temp = figure('Visible', 'off');
    
    h = phasors([50 * I_complex(i), T_e{i, 1}]);
    nume_exp = T_e.Properties.RowNames{i};
    title(['Diagrama Fazoriala - ', strrep(nume_exp, '_', '\_')], 'FontSize', 12);
    legend(h, {'Curent I (\times50)', 'Tensiune U [V]'}, 'Location', 'northeast');
    
    nume_imagine = fullfile(folder_imagini, [nume_exp, '_fazori.png']);
    exportgraphics(fig_temp, nume_imagine, 'Resolution', 300);
    close(fig_temp);
end

disp(['Toate cele ', num2str(height(T_e)), ' imagini au fost salvate in: ', folder_imagini]);
disp('exit code: 0 -- Totul e ok')
toc